spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/itmo-demo
    username: postgres
    password: 357
    driver-class-name: org.postgresql.Driver

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 2
    consumer:
      client-id: itmmo-server-client
      group-id: group
      enable-auto-commit: true
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 180000
        loggerLevel: basic

logging:
  level:
    org:
      hibernate:
        type: trace

app:
  base-url: itmo.ru

kafka:
  topics:
    notification: itmo

